import { Inter } from "next/font/google";
import "@/app/globals.css"; //tailwindcss
import StyledComponentsRegistry from "@/lib/AntRegistry";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <ClerkProvider
      appearance={{
        signIn: {
          variables: { colorPrimary: "#3B82F6" },
        },
        signUp: {
          variables: { colorPrimary: "#3B82F6" },
        },
      }}
    >
      <html lang="en" className="dark:bg-black">
        <body className={inter.className}>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </body>
      </html>
    </ClerkProvider>
  );
}
